package catalog

import "strings"

// inflections returns term first, then the singular and plural forms of its
// last word, so "tomatoes", "tomato" and "cherry tomatoes" all find their
// entry. The forms are generated by suffix rules, not validated: the database
// decides which of them exist. term must already be normalized.
func inflections(term string) []string {
	if term == "" {
		return nil
	}
	head, last := "", term
	if i := strings.LastIndexByte(term, ' '); i >= 0 {
		head, last = term[:i+1], term[i+1:]
	}
	out := []string{term}
	seen := map[string]bool{term: true}
	add := func(w string) {
		if w == "" || seen[head+w] {
			return
		}
		seen[head+w] = true
		out = append(out, head+w)
	}
	for _, w := range singulars(last) {
		add(w)
	}
	for _, w := range plurals(last) {
		add(w)
	}
	return out
}

func singulars(w string) []string {
	var out []string
	switch {
	case strings.HasSuffix(w, "ies") && len(w) > 3:
		out = append(out, strings.TrimSuffix(w, "ies")+"y")
	case strings.HasSuffix(w, "ves") && len(w) > 3:
		stem := strings.TrimSuffix(w, "ves")
		out = append(out, stem+"f", stem+"fe")
	}
	if strings.HasSuffix(w, "es") && len(w) > 2 {
		out = append(out, strings.TrimSuffix(w, "es"))
	}
	if strings.HasSuffix(w, "s") && !strings.HasSuffix(w, "ss") && len(w) > 1 {
		out = append(out, strings.TrimSuffix(w, "s"))
	}
	return out
}

func plurals(w string) []string {
	out := []string{w + "s", w + "es"}
	switch {
	case strings.HasSuffix(w, "y"):
		out = append(out, strings.TrimSuffix(w, "y")+"ies")
	case strings.HasSuffix(w, "fe"):
		out = append(out, strings.TrimSuffix(w, "fe")+"ves")
	case strings.HasSuffix(w, "f"):
		out = append(out, strings.TrimSuffix(w, "f")+"ves")
	}
	return out
}
