-- +goose Up
-- Catalog: canonical ingredients, units and equipment with their aliases
-- (ADR-00008, ADR-00005). Names and aliases are stored trimmed and lower-case
-- by the catalog package; the UNIQUE constraints rely on that.
-- unit.factor is the exact number of base units (g, ml, each) in one unit,
-- as text in a form quantity.ParseRat reads. It is NULL for dimension 'other'.
-- ingredients.density_g_per_ml is grams per millilitre and NULL when unknown.

CREATE TABLE units (
    id        INTEGER PRIMARY KEY,
    name      TEXT NOT NULL UNIQUE CHECK (name <> ''),
    system    TEXT NOT NULL CHECK (system IN ('us', 'metric', 'none')),
    dimension TEXT NOT NULL CHECK (dimension IN ('mass', 'volume', 'count', 'other')),
    factor    TEXT CHECK (factor IS NULL OR factor <> ''),
    reviewed  INTEGER NOT NULL DEFAULT 0 CHECK (reviewed IN (0, 1)),
    CHECK ((dimension = 'other' AND factor IS NULL) OR (dimension <> 'other' AND factor IS NOT NULL))
);

CREATE TABLE unit_aliases (
    alias   TEXT PRIMARY KEY CHECK (alias <> ''),
    unit_id INTEGER NOT NULL REFERENCES units (id) ON DELETE CASCADE
);
CREATE INDEX unit_aliases_unit_id ON unit_aliases (unit_id);

CREATE TABLE ingredients (
    id               INTEGER PRIMARY KEY,
    name             TEXT NOT NULL UNIQUE CHECK (name <> ''),
    aisle            TEXT NOT NULL CHECK (aisle <> ''),
    density_g_per_ml REAL CHECK (density_g_per_ml IS NULL OR density_g_per_ml > 0),
    usda_fdc_id      INTEGER UNIQUE CHECK (usda_fdc_id IS NULL OR usda_fdc_id > 0),
    reviewed         INTEGER NOT NULL DEFAULT 0 CHECK (reviewed IN (0, 1))
);

CREATE TABLE ingredient_aliases (
    alias         TEXT PRIMARY KEY CHECK (alias <> ''),
    ingredient_id INTEGER NOT NULL REFERENCES ingredients (id) ON DELETE CASCADE
);
CREATE INDEX ingredient_aliases_ingredient_id ON ingredient_aliases (ingredient_id);

CREATE TABLE equipment (
    id       INTEGER PRIMARY KEY,
    name     TEXT NOT NULL UNIQUE CHECK (name <> ''),
    reviewed INTEGER NOT NULL DEFAULT 0 CHECK (reviewed IN (0, 1))
);

CREATE TABLE equipment_aliases (
    alias        TEXT PRIMARY KEY CHECK (alias <> ''),
    equipment_id INTEGER NOT NULL REFERENCES equipment (id) ON DELETE CASCADE
);
CREATE INDEX equipment_aliases_equipment_id ON equipment_aliases (equipment_id);

-- Seed: curated units, ingredients and equipment (internal/catalog/seed).
-- Unit systems, dimensions and factors are quantity's built-in table.

INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('g', 'metric', 'mass', '1', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('gram', (SELECT id FROM units WHERE name = 'g'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('grams', (SELECT id FROM units WHERE name = 'g'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('gm', (SELECT id FROM units WHERE name = 'g'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('gms', (SELECT id FROM units WHERE name = 'g'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('kg', 'metric', 'mass', '1000', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('kilogram', (SELECT id FROM units WHERE name = 'kg'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('kilograms', (SELECT id FROM units WHERE name = 'kg'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('kgs', (SELECT id FROM units WHERE name = 'kg'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('kilo', (SELECT id FROM units WHERE name = 'kg'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('kilos', (SELECT id FROM units WHERE name = 'kg'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('oz', 'us', 'mass', '28 559237/1600000', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('ounce', (SELECT id FROM units WHERE name = 'oz'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('ounces', (SELECT id FROM units WHERE name = 'oz'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('ozs', (SELECT id FROM units WHERE name = 'oz'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('lb', 'us', 'mass', '453 59237/100000', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('pound', (SELECT id FROM units WHERE name = 'lb'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('pounds', (SELECT id FROM units WHERE name = 'lb'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('lbs', (SELECT id FROM units WHERE name = 'lb'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('lb.', (SELECT id FROM units WHERE name = 'lb'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('ml', 'metric', 'volume', '1', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('milliliter', (SELECT id FROM units WHERE name = 'ml'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('milliliters', (SELECT id FROM units WHERE name = 'ml'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('millilitre', (SELECT id FROM units WHERE name = 'ml'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('millilitres', (SELECT id FROM units WHERE name = 'ml'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('mls', (SELECT id FROM units WHERE name = 'ml'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('l', 'metric', 'volume', '1000', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('liter', (SELECT id FROM units WHERE name = 'l'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('liters', (SELECT id FROM units WHERE name = 'l'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('litre', (SELECT id FROM units WHERE name = 'l'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('litres', (SELECT id FROM units WHERE name = 'l'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('tsp', 'us', 'volume', '4 29725491/32000000', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('teaspoon', (SELECT id FROM units WHERE name = 'tsp'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('teaspoons', (SELECT id FROM units WHERE name = 'tsp'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('tsps', (SELECT id FROM units WHERE name = 'tsp'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('tbsp', 'us', 'volume', '14 25176473/32000000', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('tablespoon', (SELECT id FROM units WHERE name = 'tbsp'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('tablespoons', (SELECT id FROM units WHERE name = 'tbsp'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('tbsps', (SELECT id FROM units WHERE name = 'tbsp'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('tbs', (SELECT id FROM units WHERE name = 'tbsp'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('tbl', (SELECT id FROM units WHERE name = 'tbsp'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('fl oz', 'us', 'volume', '29 9176473/16000000', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('fluid ounce', (SELECT id FROM units WHERE name = 'fl oz'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('fluid ounces', (SELECT id FROM units WHERE name = 'fl oz'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('fl. oz', (SELECT id FROM units WHERE name = 'fl oz'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('fl. oz.', (SELECT id FROM units WHERE name = 'fl oz'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('cup', 'us', 'volume', '236 1176473/2000000', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('cups', (SELECT id FROM units WHERE name = 'cup'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('pint', 'us', 'volume', '473 176473/1000000', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('pints', (SELECT id FROM units WHERE name = 'pint'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('pt', (SELECT id FROM units WHERE name = 'pint'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('pts', (SELECT id FROM units WHERE name = 'pint'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('quart', 'us', 'volume', '946 176473/500000', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('quarts', (SELECT id FROM units WHERE name = 'quart'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('qt', (SELECT id FROM units WHERE name = 'quart'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('qts', (SELECT id FROM units WHERE name = 'quart'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('gallon', 'us', 'volume', '3785 51473/125000', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('gallons', (SELECT id FROM units WHERE name = 'gallon'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('gal', (SELECT id FROM units WHERE name = 'gallon'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('each', 'none', 'count', '1', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('ea', (SELECT id FROM units WHERE name = 'each'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('piece', (SELECT id FROM units WHERE name = 'each'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('pieces', (SELECT id FROM units WHERE name = 'each'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('dozen', 'none', 'count', '12', 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('dozens', (SELECT id FROM units WHERE name = 'dozen'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('doz', (SELECT id FROM units WHERE name = 'dozen'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('pinch', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('pinches', (SELECT id FROM units WHERE name = 'pinch'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('dash', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('dashes', (SELECT id FROM units WHERE name = 'dash'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('clove', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('cloves', (SELECT id FROM units WHERE name = 'clove'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('can', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('cans', (SELECT id FROM units WHERE name = 'can'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('tin', (SELECT id FROM units WHERE name = 'can'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('tins', (SELECT id FROM units WHERE name = 'can'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('bunch', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('bunches', (SELECT id FROM units WHERE name = 'bunch'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('sprig', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('sprigs', (SELECT id FROM units WHERE name = 'sprig'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('stick', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('sticks', (SELECT id FROM units WHERE name = 'stick'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('slice', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('slices', (SELECT id FROM units WHERE name = 'slice'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('package', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('packages', (SELECT id FROM units WHERE name = 'package'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('pkg', (SELECT id FROM units WHERE name = 'package'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('packet', (SELECT id FROM units WHERE name = 'package'));
INSERT INTO unit_aliases (alias, unit_id) VALUES ('packets', (SELECT id FROM units WHERE name = 'package'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('jar', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('jars', (SELECT id FROM units WHERE name = 'jar'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('bottle', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('bottles', (SELECT id FROM units WHERE name = 'bottle'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('head', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('heads', (SELECT id FROM units WHERE name = 'head'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('stalk', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('stalks', (SELECT id FROM units WHERE name = 'stalk'));
INSERT INTO units (name, system, dimension, factor, reviewed) VALUES ('handful', 'none', 'other', NULL, 1);
INSERT INTO unit_aliases (alias, unit_id) VALUES ('handfuls', (SELECT id FROM units WHERE name = 'handful'));

INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('onion', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('onions', (SELECT id FROM ingredients WHERE name = 'onion'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('yellow onion', (SELECT id FROM ingredients WHERE name = 'onion'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('yellow onions', (SELECT id FROM ingredients WHERE name = 'onion'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('red onion', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('red onions', (SELECT id FROM ingredients WHERE name = 'red onion'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('green onion', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('green onions', (SELECT id FROM ingredients WHERE name = 'green onion'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('scallion', (SELECT id FROM ingredients WHERE name = 'green onion'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('scallions', (SELECT id FROM ingredients WHERE name = 'green onion'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('spring onion', (SELECT id FROM ingredients WHERE name = 'green onion'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('spring onions', (SELECT id FROM ingredients WHERE name = 'green onion'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('shallot', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('shallots', (SELECT id FROM ingredients WHERE name = 'shallot'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('leek', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('leeks', (SELECT id FROM ingredients WHERE name = 'leek'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('garlic', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('garlic clove', (SELECT id FROM ingredients WHERE name = 'garlic'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('garlic cloves', (SELECT id FROM ingredients WHERE name = 'garlic'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cloves garlic', (SELECT id FROM ingredients WHERE name = 'garlic'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('ginger', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('fresh ginger', (SELECT id FROM ingredients WHERE name = 'ginger'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('ginger root', (SELECT id FROM ingredients WHERE name = 'ginger'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('carrot', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('carrots', (SELECT id FROM ingredients WHERE name = 'carrot'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('celery', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('celery stalk', (SELECT id FROM ingredients WHERE name = 'celery'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('celery stalks', (SELECT id FROM ingredients WHERE name = 'celery'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('celery rib', (SELECT id FROM ingredients WHERE name = 'celery'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('celery ribs', (SELECT id FROM ingredients WHERE name = 'celery'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('potato', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('potatoes', (SELECT id FROM ingredients WHERE name = 'potato'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('sweet potato', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sweet potatoes', (SELECT id FROM ingredients WHERE name = 'sweet potato'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('yam', (SELECT id FROM ingredients WHERE name = 'sweet potato'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('yams', (SELECT id FROM ingredients WHERE name = 'sweet potato'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('tomato', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('tomatoes', (SELECT id FROM ingredients WHERE name = 'tomato'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('cherry tomato', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cherry tomatoes', (SELECT id FROM ingredients WHERE name = 'cherry tomato'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('grape tomato', (SELECT id FROM ingredients WHERE name = 'cherry tomato'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('grape tomatoes', (SELECT id FROM ingredients WHERE name = 'cherry tomato'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('bell pepper', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('bell peppers', (SELECT id FROM ingredients WHERE name = 'bell pepper'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sweet pepper', (SELECT id FROM ingredients WHERE name = 'bell pepper'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sweet peppers', (SELECT id FROM ingredients WHERE name = 'bell pepper'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('jalapeno', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('jalapeno pepper', (SELECT id FROM ingredients WHERE name = 'jalapeno'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('jalapeno peppers', (SELECT id FROM ingredients WHERE name = 'jalapeno'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('jalapeño', (SELECT id FROM ingredients WHERE name = 'jalapeno'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('jalapeños', (SELECT id FROM ingredients WHERE name = 'jalapeno'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('chili pepper', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chili peppers', (SELECT id FROM ingredients WHERE name = 'chili pepper'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chile pepper', (SELECT id FROM ingredients WHERE name = 'chili pepper'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chile peppers', (SELECT id FROM ingredients WHERE name = 'chili pepper'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chilli', (SELECT id FROM ingredients WHERE name = 'chili pepper'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('cucumber', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cucumbers', (SELECT id FROM ingredients WHERE name = 'cucumber'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('zucchini', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('zucchinis', (SELECT id FROM ingredients WHERE name = 'zucchini'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('courgette', (SELECT id FROM ingredients WHERE name = 'zucchini'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('courgettes', (SELECT id FROM ingredients WHERE name = 'zucchini'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('eggplant', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('eggplants', (SELECT id FROM ingredients WHERE name = 'eggplant'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('aubergine', (SELECT id FROM ingredients WHERE name = 'eggplant'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('aubergines', (SELECT id FROM ingredients WHERE name = 'eggplant'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('broccoli', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('broccoli florets', (SELECT id FROM ingredients WHERE name = 'broccoli'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('broccoli crowns', (SELECT id FROM ingredients WHERE name = 'broccoli'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('cauliflower', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cauliflower florets', (SELECT id FROM ingredients WHERE name = 'cauliflower'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cauliflowers', (SELECT id FROM ingredients WHERE name = 'cauliflower'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('spinach', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('baby spinach', (SELECT id FROM ingredients WHERE name = 'spinach'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('spinach leaves', (SELECT id FROM ingredients WHERE name = 'spinach'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('kale', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('kale leaves', (SELECT id FROM ingredients WHERE name = 'kale'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('curly kale', (SELECT id FROM ingredients WHERE name = 'kale'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('lettuce', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('romaine', (SELECT id FROM ingredients WHERE name = 'lettuce'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('romaine lettuce', (SELECT id FROM ingredients WHERE name = 'lettuce'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('iceberg lettuce', (SELECT id FROM ingredients WHERE name = 'lettuce'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('cabbage', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cabbages', (SELECT id FROM ingredients WHERE name = 'cabbage'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('green cabbage', (SELECT id FROM ingredients WHERE name = 'cabbage'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('mushroom', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('mushrooms', (SELECT id FROM ingredients WHERE name = 'mushroom'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('button mushroom', (SELECT id FROM ingredients WHERE name = 'mushroom'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('button mushrooms', (SELECT id FROM ingredients WHERE name = 'mushroom'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cremini mushrooms', (SELECT id FROM ingredients WHERE name = 'mushroom'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('corn', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('corn kernels', (SELECT id FROM ingredients WHERE name = 'corn'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sweet corn', (SELECT id FROM ingredients WHERE name = 'corn'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('corn on the cob', (SELECT id FROM ingredients WHERE name = 'corn'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('green bean', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('green beans', (SELECT id FROM ingredients WHERE name = 'green bean'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('string beans', (SELECT id FROM ingredients WHERE name = 'green bean'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('asparagus', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('asparagus spears', (SELECT id FROM ingredients WHERE name = 'asparagus'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('avocado', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('avocados', (SELECT id FROM ingredients WHERE name = 'avocado'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('lemon', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('lemons', (SELECT id FROM ingredients WHERE name = 'lemon'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('lime', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('limes', (SELECT id FROM ingredients WHERE name = 'lime'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('orange', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('oranges', (SELECT id FROM ingredients WHERE name = 'orange'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('apple', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('apples', (SELECT id FROM ingredients WHERE name = 'apple'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('banana', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('bananas', (SELECT id FROM ingredients WHERE name = 'banana'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('strawberry', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('strawberries', (SELECT id FROM ingredients WHERE name = 'strawberry'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('blueberry', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('blueberries', (SELECT id FROM ingredients WHERE name = 'blueberry'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('raspberry', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('raspberries', (SELECT id FROM ingredients WHERE name = 'raspberry'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('grape', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('grapes', (SELECT id FROM ingredients WHERE name = 'grape'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('pineapple', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pineapples', (SELECT id FROM ingredients WHERE name = 'pineapple'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('mango', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('mangoes', (SELECT id FROM ingredients WHERE name = 'mango'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('mangos', (SELECT id FROM ingredients WHERE name = 'mango'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('peach', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('peaches', (SELECT id FROM ingredients WHERE name = 'peach'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('pear', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pears', (SELECT id FROM ingredients WHERE name = 'pear'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('fresh parsley', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('parsley', (SELECT id FROM ingredients WHERE name = 'fresh parsley'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('flat-leaf parsley', (SELECT id FROM ingredients WHERE name = 'fresh parsley'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('italian parsley', (SELECT id FROM ingredients WHERE name = 'fresh parsley'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('fresh cilantro', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cilantro', (SELECT id FROM ingredients WHERE name = 'fresh cilantro'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('coriander leaves', (SELECT id FROM ingredients WHERE name = 'fresh cilantro'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('fresh coriander', (SELECT id FROM ingredients WHERE name = 'fresh cilantro'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('fresh basil', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('basil', (SELECT id FROM ingredients WHERE name = 'fresh basil'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('basil leaves', (SELECT id FROM ingredients WHERE name = 'fresh basil'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('fresh mint', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('mint', (SELECT id FROM ingredients WHERE name = 'fresh mint'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('mint leaves', (SELECT id FROM ingredients WHERE name = 'fresh mint'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('fresh thyme', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('thyme sprigs', (SELECT id FROM ingredients WHERE name = 'fresh thyme'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('fresh thyme leaves', (SELECT id FROM ingredients WHERE name = 'fresh thyme'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('fresh rosemary', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('rosemary', (SELECT id FROM ingredients WHERE name = 'fresh rosemary'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('rosemary sprigs', (SELECT id FROM ingredients WHERE name = 'fresh rosemary'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('fresh dill', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('dill', (SELECT id FROM ingredients WHERE name = 'fresh dill'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('dill weed', (SELECT id FROM ingredients WHERE name = 'fresh dill'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('fresh chives', 'produce', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chives', (SELECT id FROM ingredients WHERE name = 'fresh chives'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('chicken breast', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chicken breasts', (SELECT id FROM ingredients WHERE name = 'chicken breast'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('boneless skinless chicken breast', (SELECT id FROM ingredients WHERE name = 'chicken breast'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('boneless skinless chicken breasts', (SELECT id FROM ingredients WHERE name = 'chicken breast'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('chicken thigh', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chicken thighs', (SELECT id FROM ingredients WHERE name = 'chicken thigh'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('boneless skinless chicken thighs', (SELECT id FROM ingredients WHERE name = 'chicken thigh'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('whole chicken', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chicken', (SELECT id FROM ingredients WHERE name = 'whole chicken'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('roasting chicken', (SELECT id FROM ingredients WHERE name = 'whole chicken'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('ground beef', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('minced beef', (SELECT id FROM ingredients WHERE name = 'ground beef'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('beef mince', (SELECT id FROM ingredients WHERE name = 'ground beef'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('beef chuck', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chuck roast', (SELECT id FROM ingredients WHERE name = 'beef chuck'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('beef chuck roast', (SELECT id FROM ingredients WHERE name = 'beef chuck'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('steak', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('steaks', (SELECT id FROM ingredients WHERE name = 'steak'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('beef steak', (SELECT id FROM ingredients WHERE name = 'steak'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sirloin steak', (SELECT id FROM ingredients WHERE name = 'steak'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('ground pork', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('minced pork', (SELECT id FROM ingredients WHERE name = 'ground pork'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pork mince', (SELECT id FROM ingredients WHERE name = 'ground pork'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('pork chop', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pork chops', (SELECT id FROM ingredients WHERE name = 'pork chop'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('pork shoulder', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pork butt', (SELECT id FROM ingredients WHERE name = 'pork shoulder'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('boston butt', (SELECT id FROM ingredients WHERE name = 'pork shoulder'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('bacon', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('bacon slices', (SELECT id FROM ingredients WHERE name = 'bacon'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('bacon strips', (SELECT id FROM ingredients WHERE name = 'bacon'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('streaky bacon', (SELECT id FROM ingredients WHERE name = 'bacon'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('sausage', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sausages', (SELECT id FROM ingredients WHERE name = 'sausage'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('italian sausage', (SELECT id FROM ingredients WHERE name = 'sausage'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('ham', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sliced ham', (SELECT id FROM ingredients WHERE name = 'ham'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cooked ham', (SELECT id FROM ingredients WHERE name = 'ham'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('ground turkey', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('turkey mince', (SELECT id FROM ingredients WHERE name = 'ground turkey'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('salmon', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('salmon fillet', (SELECT id FROM ingredients WHERE name = 'salmon'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('salmon fillets', (SELECT id FROM ingredients WHERE name = 'salmon'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('shrimp', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('prawns', (SELECT id FROM ingredients WHERE name = 'shrimp'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('prawn', (SELECT id FROM ingredients WHERE name = 'shrimp'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('large shrimp', (SELECT id FROM ingredients WHERE name = 'shrimp'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('white fish', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cod', (SELECT id FROM ingredients WHERE name = 'white fish'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cod fillet', (SELECT id FROM ingredients WHERE name = 'white fish'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('white fish fillets', (SELECT id FROM ingredients WHERE name = 'white fish'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('tuna', 'meat & seafood', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('canned tuna', (SELECT id FROM ingredients WHERE name = 'tuna'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('tuna steak', (SELECT id FROM ingredients WHERE name = 'tuna'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('egg', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('eggs', (SELECT id FROM ingredients WHERE name = 'egg'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('large egg', (SELECT id FROM ingredients WHERE name = 'egg'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('large eggs', (SELECT id FROM ingredients WHERE name = 'egg'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('egg yolk', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('egg yolks', (SELECT id FROM ingredients WHERE name = 'egg yolk'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('yolk', (SELECT id FROM ingredients WHERE name = 'egg yolk'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('yolks', (SELECT id FROM ingredients WHERE name = 'egg yolk'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('egg white', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('egg whites', (SELECT id FROM ingredients WHERE name = 'egg white'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('white of egg', (SELECT id FROM ingredients WHERE name = 'egg white'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('butter', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('unsalted butter', (SELECT id FROM ingredients WHERE name = 'butter'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('salted butter', (SELECT id FROM ingredients WHERE name = 'butter'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sweet butter', (SELECT id FROM ingredients WHERE name = 'butter'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('milk', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('whole milk', (SELECT id FROM ingredients WHERE name = 'milk'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('full-fat milk', (SELECT id FROM ingredients WHERE name = 'milk'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('2% milk', (SELECT id FROM ingredients WHERE name = 'milk'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('heavy cream', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('heavy whipping cream', (SELECT id FROM ingredients WHERE name = 'heavy cream'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('whipping cream', (SELECT id FROM ingredients WHERE name = 'heavy cream'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('double cream', (SELECT id FROM ingredients WHERE name = 'heavy cream'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('half and half', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('half-and-half', (SELECT id FROM ingredients WHERE name = 'half and half'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('sour cream', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('soured cream', (SELECT id FROM ingredients WHERE name = 'sour cream'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('buttermilk', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cultured buttermilk', (SELECT id FROM ingredients WHERE name = 'buttermilk'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('yogurt', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('plain yogurt', (SELECT id FROM ingredients WHERE name = 'yogurt'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('yoghurt', (SELECT id FROM ingredients WHERE name = 'yogurt'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('natural yogurt', (SELECT id FROM ingredients WHERE name = 'yogurt'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('greek yogurt', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('greek yoghurt', (SELECT id FROM ingredients WHERE name = 'greek yogurt'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('plain greek yogurt', (SELECT id FROM ingredients WHERE name = 'greek yogurt'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('cream cheese', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('soft cream cheese', (SELECT id FROM ingredients WHERE name = 'cream cheese'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('cheddar cheese', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cheddar', (SELECT id FROM ingredients WHERE name = 'cheddar cheese'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sharp cheddar', (SELECT id FROM ingredients WHERE name = 'cheddar cheese'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('shredded cheddar', (SELECT id FROM ingredients WHERE name = 'cheddar cheese'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('mozzarella', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('mozzarella cheese', (SELECT id FROM ingredients WHERE name = 'mozzarella'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('shredded mozzarella', (SELECT id FROM ingredients WHERE name = 'mozzarella'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('parmesan', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('parmesan cheese', (SELECT id FROM ingredients WHERE name = 'parmesan'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('parmigiano reggiano', (SELECT id FROM ingredients WHERE name = 'parmesan'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('grated parmesan', (SELECT id FROM ingredients WHERE name = 'parmesan'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('feta', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('feta cheese', (SELECT id FROM ingredients WHERE name = 'feta'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('crumbled feta', (SELECT id FROM ingredients WHERE name = 'feta'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('ricotta', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('ricotta cheese', (SELECT id FROM ingredients WHERE name = 'ricotta'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('cottage cheese', 'dairy & eggs', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('small curd cottage cheese', (SELECT id FROM ingredients WHERE name = 'cottage cheese'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('bread', 'bakery', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('loaf of bread', (SELECT id FROM ingredients WHERE name = 'bread'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sandwich bread', (SELECT id FROM ingredients WHERE name = 'bread'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('white bread', (SELECT id FROM ingredients WHERE name = 'bread'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('breadcrumbs', 'bakery', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('bread crumbs', (SELECT id FROM ingredients WHERE name = 'breadcrumbs'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('dry breadcrumbs', (SELECT id FROM ingredients WHERE name = 'breadcrumbs'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('dried breadcrumbs', (SELECT id FROM ingredients WHERE name = 'breadcrumbs'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('panko', 'bakery', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('panko breadcrumbs', (SELECT id FROM ingredients WHERE name = 'panko'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('panko bread crumbs', (SELECT id FROM ingredients WHERE name = 'panko'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('tortilla', 'bakery', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('tortillas', (SELECT id FROM ingredients WHERE name = 'tortilla'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('flour tortillas', (SELECT id FROM ingredients WHERE name = 'tortilla'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('corn tortillas', (SELECT id FROM ingredients WHERE name = 'tortilla'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('hamburger bun', 'bakery', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('hamburger buns', (SELECT id FROM ingredients WHERE name = 'hamburger bun'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('burger buns', (SELECT id FROM ingredients WHERE name = 'hamburger bun'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('pita bread', 'bakery', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pita', (SELECT id FROM ingredients WHERE name = 'pita bread'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pitas', (SELECT id FROM ingredients WHERE name = 'pita bread'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pita breads', (SELECT id FROM ingredients WHERE name = 'pita bread'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('all-purpose flour', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('flour', (SELECT id FROM ingredients WHERE name = 'all-purpose flour'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('plain flour', (SELECT id FROM ingredients WHERE name = 'all-purpose flour'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('ap flour', (SELECT id FROM ingredients WHERE name = 'all-purpose flour'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('white flour', (SELECT id FROM ingredients WHERE name = 'all-purpose flour'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('bread flour', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('strong flour', (SELECT id FROM ingredients WHERE name = 'bread flour'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('strong white flour', (SELECT id FROM ingredients WHERE name = 'bread flour'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('whole wheat flour', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('wholemeal flour', (SELECT id FROM ingredients WHERE name = 'whole wheat flour'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('whole-wheat flour', (SELECT id FROM ingredients WHERE name = 'whole wheat flour'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('cornstarch', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('corn starch', (SELECT id FROM ingredients WHERE name = 'cornstarch'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cornflour', (SELECT id FROM ingredients WHERE name = 'cornstarch'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('baking powder', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('double-acting baking powder', (SELECT id FROM ingredients WHERE name = 'baking powder'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('baking soda', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('bicarbonate of soda', (SELECT id FROM ingredients WHERE name = 'baking soda'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('bicarb', (SELECT id FROM ingredients WHERE name = 'baking soda'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sodium bicarbonate', (SELECT id FROM ingredients WHERE name = 'baking soda'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('active dry yeast', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('dry yeast', (SELECT id FROM ingredients WHERE name = 'active dry yeast'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('yeast', (SELECT id FROM ingredients WHERE name = 'active dry yeast'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('instant yeast', (SELECT id FROM ingredients WHERE name = 'active dry yeast'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('granulated sugar', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sugar', (SELECT id FROM ingredients WHERE name = 'granulated sugar'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('white sugar', (SELECT id FROM ingredients WHERE name = 'granulated sugar'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('caster sugar', (SELECT id FROM ingredients WHERE name = 'granulated sugar'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('superfine sugar', (SELECT id FROM ingredients WHERE name = 'granulated sugar'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('brown sugar', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('light brown sugar', (SELECT id FROM ingredients WHERE name = 'brown sugar'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('dark brown sugar', (SELECT id FROM ingredients WHERE name = 'brown sugar'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('packed brown sugar', (SELECT id FROM ingredients WHERE name = 'brown sugar'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('powdered sugar', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('confectioners sugar', (SELECT id FROM ingredients WHERE name = 'powdered sugar'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('confectioners'' sugar', (SELECT id FROM ingredients WHERE name = 'powdered sugar'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('icing sugar', (SELECT id FROM ingredients WHERE name = 'powdered sugar'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('honey', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('runny honey', (SELECT id FROM ingredients WHERE name = 'honey'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('raw honey', (SELECT id FROM ingredients WHERE name = 'honey'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('maple syrup', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pure maple syrup', (SELECT id FROM ingredients WHERE name = 'maple syrup'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('molasses', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('blackstrap molasses', (SELECT id FROM ingredients WHERE name = 'molasses'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('vanilla extract', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pure vanilla extract', (SELECT id FROM ingredients WHERE name = 'vanilla extract'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('vanilla essence', (SELECT id FROM ingredients WHERE name = 'vanilla extract'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('chocolate chips', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('semisweet chocolate chips', (SELECT id FROM ingredients WHERE name = 'chocolate chips'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chocolate chunks', (SELECT id FROM ingredients WHERE name = 'chocolate chips'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('cocoa powder', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('unsweetened cocoa powder', (SELECT id FROM ingredients WHERE name = 'cocoa powder'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cocoa', (SELECT id FROM ingredients WHERE name = 'cocoa powder'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cacao powder', (SELECT id FROM ingredients WHERE name = 'cocoa powder'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('dark chocolate', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('bittersweet chocolate', (SELECT id FROM ingredients WHERE name = 'dark chocolate'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('semisweet chocolate', (SELECT id FROM ingredients WHERE name = 'dark chocolate'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('rolled oats', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('oats', (SELECT id FROM ingredients WHERE name = 'rolled oats'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('old-fashioned oats', (SELECT id FROM ingredients WHERE name = 'rolled oats'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('porridge oats', (SELECT id FROM ingredients WHERE name = 'rolled oats'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('shredded coconut', 'baking', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('desiccated coconut', (SELECT id FROM ingredients WHERE name = 'shredded coconut'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('coconut flakes', (SELECT id FROM ingredients WHERE name = 'shredded coconut'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('salt', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('table salt', (SELECT id FROM ingredients WHERE name = 'salt'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('fine salt', (SELECT id FROM ingredients WHERE name = 'salt'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sea salt', (SELECT id FROM ingredients WHERE name = 'salt'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('kosher salt', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('coarse salt', (SELECT id FROM ingredients WHERE name = 'kosher salt'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('flaky salt', (SELECT id FROM ingredients WHERE name = 'kosher salt'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('black pepper', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('ground black pepper', (SELECT id FROM ingredients WHERE name = 'black pepper'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('freshly ground black pepper', (SELECT id FROM ingredients WHERE name = 'black pepper'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pepper', (SELECT id FROM ingredients WHERE name = 'black pepper'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('cumin', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('ground cumin', (SELECT id FROM ingredients WHERE name = 'cumin'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cumin powder', (SELECT id FROM ingredients WHERE name = 'cumin'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('paprika', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sweet paprika', (SELECT id FROM ingredients WHERE name = 'paprika'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('ground paprika', (SELECT id FROM ingredients WHERE name = 'paprika'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('smoked paprika', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pimenton', (SELECT id FROM ingredients WHERE name = 'smoked paprika'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('spanish smoked paprika', (SELECT id FROM ingredients WHERE name = 'smoked paprika'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('chili powder', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chile powder', (SELECT id FROM ingredients WHERE name = 'chili powder'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('cayenne pepper', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cayenne', (SELECT id FROM ingredients WHERE name = 'cayenne pepper'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('ground cayenne', (SELECT id FROM ingredients WHERE name = 'cayenne pepper'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('red pepper flakes', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('crushed red pepper', (SELECT id FROM ingredients WHERE name = 'red pepper flakes'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chili flakes', (SELECT id FROM ingredients WHERE name = 'red pepper flakes'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chilli flakes', (SELECT id FROM ingredients WHERE name = 'red pepper flakes'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('cinnamon', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('ground cinnamon', (SELECT id FROM ingredients WHERE name = 'cinnamon'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('nutmeg', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('ground nutmeg', (SELECT id FROM ingredients WHERE name = 'nutmeg'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('grated nutmeg', (SELECT id FROM ingredients WHERE name = 'nutmeg'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('turmeric', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('ground turmeric', (SELECT id FROM ingredients WHERE name = 'turmeric'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('turmeric powder', (SELECT id FROM ingredients WHERE name = 'turmeric'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('coriander', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('ground coriander', (SELECT id FROM ingredients WHERE name = 'coriander'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('coriander seeds', (SELECT id FROM ingredients WHERE name = 'coriander'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('oregano', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('dried oregano', (SELECT id FROM ingredients WHERE name = 'oregano'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('dried thyme', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('thyme', (SELECT id FROM ingredients WHERE name = 'dried thyme'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('dried basil', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('basil flakes', (SELECT id FROM ingredients WHERE name = 'dried basil'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('bay leaf', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('bay leaves', (SELECT id FROM ingredients WHERE name = 'bay leaf'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('dried bay leaves', (SELECT id FROM ingredients WHERE name = 'bay leaf'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('garlic powder', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('granulated garlic', (SELECT id FROM ingredients WHERE name = 'garlic powder'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('onion powder', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('granulated onion', (SELECT id FROM ingredients WHERE name = 'onion powder'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('curry powder', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('madras curry powder', (SELECT id FROM ingredients WHERE name = 'curry powder'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('italian seasoning', 'spices & seasonings', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('italian herbs', (SELECT id FROM ingredients WHERE name = 'italian seasoning'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('olive oil', 'oils & vinegars', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('extra virgin olive oil', (SELECT id FROM ingredients WHERE name = 'olive oil'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('extra-virgin olive oil', (SELECT id FROM ingredients WHERE name = 'olive oil'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('evoo', (SELECT id FROM ingredients WHERE name = 'olive oil'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('vegetable oil', 'oils & vinegars', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cooking oil', (SELECT id FROM ingredients WHERE name = 'vegetable oil'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('neutral oil', (SELECT id FROM ingredients WHERE name = 'vegetable oil'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('canola oil', (SELECT id FROM ingredients WHERE name = 'vegetable oil'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('rapeseed oil', (SELECT id FROM ingredients WHERE name = 'vegetable oil'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('sesame oil', 'oils & vinegars', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('toasted sesame oil', (SELECT id FROM ingredients WHERE name = 'sesame oil'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('coconut oil', 'oils & vinegars', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('virgin coconut oil', (SELECT id FROM ingredients WHERE name = 'coconut oil'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('white vinegar', 'oils & vinegars', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('distilled white vinegar', (SELECT id FROM ingredients WHERE name = 'white vinegar'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('distilled vinegar', (SELECT id FROM ingredients WHERE name = 'white vinegar'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('apple cider vinegar', 'oils & vinegars', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cider vinegar', (SELECT id FROM ingredients WHERE name = 'apple cider vinegar'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('acv', (SELECT id FROM ingredients WHERE name = 'apple cider vinegar'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('red wine vinegar', 'oils & vinegars', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('red-wine vinegar', (SELECT id FROM ingredients WHERE name = 'red wine vinegar'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('balsamic vinegar', 'oils & vinegars', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('balsamic', (SELECT id FROM ingredients WHERE name = 'balsamic vinegar'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('rice vinegar', 'oils & vinegars', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('rice wine vinegar', (SELECT id FROM ingredients WHERE name = 'rice vinegar'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('soy sauce', 'condiments & sauces', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('soya sauce', (SELECT id FROM ingredients WHERE name = 'soy sauce'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('shoyu', (SELECT id FROM ingredients WHERE name = 'soy sauce'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('light soy sauce', (SELECT id FROM ingredients WHERE name = 'soy sauce'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('worcestershire sauce', 'condiments & sauces', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('worcestershire', (SELECT id FROM ingredients WHERE name = 'worcestershire sauce'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('worcester sauce', (SELECT id FROM ingredients WHERE name = 'worcestershire sauce'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('hot sauce', 'condiments & sauces', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('tabasco', (SELECT id FROM ingredients WHERE name = 'hot sauce'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('louisiana hot sauce', (SELECT id FROM ingredients WHERE name = 'hot sauce'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('ketchup', 'condiments & sauces', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('tomato ketchup', (SELECT id FROM ingredients WHERE name = 'ketchup'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('catsup', (SELECT id FROM ingredients WHERE name = 'ketchup'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('mustard', 'condiments & sauces', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('yellow mustard', (SELECT id FROM ingredients WHERE name = 'mustard'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('prepared mustard', (SELECT id FROM ingredients WHERE name = 'mustard'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('dijon mustard', 'condiments & sauces', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('dijon', (SELECT id FROM ingredients WHERE name = 'dijon mustard'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('mayonnaise', 'condiments & sauces', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('mayo', (SELECT id FROM ingredients WHERE name = 'mayonnaise'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('tomato paste', 'condiments & sauces', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('tomato puree', (SELECT id FROM ingredients WHERE name = 'tomato paste'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('concentrated tomato paste', (SELECT id FROM ingredients WHERE name = 'tomato paste'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('fish sauce', 'condiments & sauces', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('nam pla', (SELECT id FROM ingredients WHERE name = 'fish sauce'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('hoisin sauce', 'condiments & sauces', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('hoisin', (SELECT id FROM ingredients WHERE name = 'hoisin sauce'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('sriracha', 'condiments & sauces', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sriracha sauce', (SELECT id FROM ingredients WHERE name = 'sriracha'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('peanut butter', 'condiments & sauces', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('smooth peanut butter', (SELECT id FROM ingredients WHERE name = 'peanut butter'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('creamy peanut butter', (SELECT id FROM ingredients WHERE name = 'peanut butter'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('canned tomatoes', 'canned goods', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('diced tomatoes', (SELECT id FROM ingredients WHERE name = 'canned tomatoes'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('canned diced tomatoes', (SELECT id FROM ingredients WHERE name = 'canned tomatoes'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('tinned tomatoes', (SELECT id FROM ingredients WHERE name = 'canned tomatoes'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('crushed tomatoes', 'canned goods', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('canned crushed tomatoes', (SELECT id FROM ingredients WHERE name = 'crushed tomatoes'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('passata', (SELECT id FROM ingredients WHERE name = 'crushed tomatoes'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('tomato sauce', 'canned goods', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('canned tomato sauce', (SELECT id FROM ingredients WHERE name = 'tomato sauce'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('chicken broth', 'canned goods', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chicken stock', (SELECT id FROM ingredients WHERE name = 'chicken broth'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chicken bouillon', (SELECT id FROM ingredients WHERE name = 'chicken broth'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('beef broth', 'canned goods', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('beef stock', (SELECT id FROM ingredients WHERE name = 'beef broth'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('beef bouillon', (SELECT id FROM ingredients WHERE name = 'beef broth'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('vegetable broth', 'canned goods', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('vegetable stock', (SELECT id FROM ingredients WHERE name = 'vegetable broth'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('veggie stock', (SELECT id FROM ingredients WHERE name = 'vegetable broth'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('coconut milk', 'canned goods', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('canned coconut milk', (SELECT id FROM ingredients WHERE name = 'coconut milk'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('full-fat coconut milk', (SELECT id FROM ingredients WHERE name = 'coconut milk'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('black beans', 'canned goods', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('canned black beans', (SELECT id FROM ingredients WHERE name = 'black beans'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('chickpeas', 'canned goods', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('garbanzo beans', (SELECT id FROM ingredients WHERE name = 'chickpeas'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('canned chickpeas', (SELECT id FROM ingredients WHERE name = 'chickpeas'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('garbanzos', (SELECT id FROM ingredients WHERE name = 'chickpeas'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('kidney beans', 'canned goods', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('red kidney beans', (SELECT id FROM ingredients WHERE name = 'kidney beans'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('canned kidney beans', (SELECT id FROM ingredients WHERE name = 'kidney beans'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('white beans', 'canned goods', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cannellini beans', (SELECT id FROM ingredients WHERE name = 'white beans'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('navy beans', (SELECT id FROM ingredients WHERE name = 'white beans'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('great northern beans', (SELECT id FROM ingredients WHERE name = 'white beans'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('white rice', 'grains & pasta', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('rice', (SELECT id FROM ingredients WHERE name = 'white rice'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('long grain rice', (SELECT id FROM ingredients WHERE name = 'white rice'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('long-grain rice', (SELECT id FROM ingredients WHERE name = 'white rice'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('basmati rice', 'grains & pasta', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('basmati', (SELECT id FROM ingredients WHERE name = 'basmati rice'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('brown rice', 'grains & pasta', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('whole grain rice', (SELECT id FROM ingredients WHERE name = 'brown rice'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('spaghetti', 'grains & pasta', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('spaghetti pasta', (SELECT id FROM ingredients WHERE name = 'spaghetti'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('penne', 'grains & pasta', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('penne pasta', (SELECT id FROM ingredients WHERE name = 'penne'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('pasta', 'grains & pasta', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('dried pasta', (SELECT id FROM ingredients WHERE name = 'pasta'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('macaroni', (SELECT id FROM ingredients WHERE name = 'pasta'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('short pasta', (SELECT id FROM ingredients WHERE name = 'pasta'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('egg noodles', 'grains & pasta', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('noodles', (SELECT id FROM ingredients WHERE name = 'egg noodles'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('wide egg noodles', (SELECT id FROM ingredients WHERE name = 'egg noodles'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('quinoa', 'grains & pasta', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('white quinoa', (SELECT id FROM ingredients WHERE name = 'quinoa'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('couscous', 'grains & pasta', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pearl couscous', (SELECT id FROM ingredients WHERE name = 'couscous'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('lentils', 'grains & pasta', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('brown lentils', (SELECT id FROM ingredients WHERE name = 'lentils'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('green lentils', (SELECT id FROM ingredients WHERE name = 'lentils'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('red lentils', (SELECT id FROM ingredients WHERE name = 'lentils'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('almonds', 'snacks & nuts', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('whole almonds', (SELECT id FROM ingredients WHERE name = 'almonds'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sliced almonds', (SELECT id FROM ingredients WHERE name = 'almonds'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('slivered almonds', (SELECT id FROM ingredients WHERE name = 'almonds'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('walnuts', 'snacks & nuts', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('walnut halves', (SELECT id FROM ingredients WHERE name = 'walnuts'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chopped walnuts', (SELECT id FROM ingredients WHERE name = 'walnuts'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('pecans', 'snacks & nuts', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pecan halves', (SELECT id FROM ingredients WHERE name = 'pecans'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('chopped pecans', (SELECT id FROM ingredients WHERE name = 'pecans'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('peanuts', 'snacks & nuts', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('roasted peanuts', (SELECT id FROM ingredients WHERE name = 'peanuts'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('unsalted peanuts', (SELECT id FROM ingredients WHERE name = 'peanuts'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('pine nuts', 'snacks & nuts', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pine kernels', (SELECT id FROM ingredients WHERE name = 'pine nuts'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('pignoli', (SELECT id FROM ingredients WHERE name = 'pine nuts'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('sesame seeds', 'snacks & nuts', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('toasted sesame seeds', (SELECT id FROM ingredients WHERE name = 'sesame seeds'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('raisins', 'snacks & nuts', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sultanas', (SELECT id FROM ingredients WHERE name = 'raisins'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('sunflower seeds', 'snacks & nuts', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('sunflower kernels', (SELECT id FROM ingredients WHERE name = 'sunflower seeds'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('water', 'beverages', 1, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('cold water', (SELECT id FROM ingredients WHERE name = 'water'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('warm water', (SELECT id FROM ingredients WHERE name = 'water'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('hot water', (SELECT id FROM ingredients WHERE name = 'water'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('boiling water', (SELECT id FROM ingredients WHERE name = 'water'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('white wine', 'beverages', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('dry white wine', (SELECT id FROM ingredients WHERE name = 'white wine'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('red wine', 'beverages', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('dry red wine', (SELECT id FROM ingredients WHERE name = 'red wine'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('beer', 'beverages', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('lager', (SELECT id FROM ingredients WHERE name = 'beer'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('frozen peas', 'frozen', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('peas', (SELECT id FROM ingredients WHERE name = 'frozen peas'));
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('green peas', (SELECT id FROM ingredients WHERE name = 'frozen peas'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('frozen spinach', 'frozen', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('frozen chopped spinach', (SELECT id FROM ingredients WHERE name = 'frozen spinach'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('frozen corn', 'frozen', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('frozen corn kernels', (SELECT id FROM ingredients WHERE name = 'frozen corn'));
INSERT INTO ingredients (name, aisle, density_g_per_ml, reviewed) VALUES ('ice', 'frozen', NULL, 1);
INSERT INTO ingredient_aliases (alias, ingredient_id) VALUES ('ice cubes', (SELECT id FROM ingredients WHERE name = 'ice'));

INSERT INTO equipment (name, reviewed) VALUES ('skillet', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('frying pan', (SELECT id FROM equipment WHERE name = 'skillet'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('fry pan', (SELECT id FROM equipment WHERE name = 'skillet'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('sauté pan', (SELECT id FROM equipment WHERE name = 'skillet'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('saute pan', (SELECT id FROM equipment WHERE name = 'skillet'));
INSERT INTO equipment (name, reviewed) VALUES ('saucepan', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('sauce pan', (SELECT id FROM equipment WHERE name = 'saucepan'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('pot', (SELECT id FROM equipment WHERE name = 'saucepan'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('small pot', (SELECT id FROM equipment WHERE name = 'saucepan'));
INSERT INTO equipment (name, reviewed) VALUES ('stockpot', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('stock pot', (SELECT id FROM equipment WHERE name = 'stockpot'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('large pot', (SELECT id FROM equipment WHERE name = 'stockpot'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('soup pot', (SELECT id FROM equipment WHERE name = 'stockpot'));
INSERT INTO equipment (name, reviewed) VALUES ('dutch oven', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('dutch pot', (SELECT id FROM equipment WHERE name = 'dutch oven'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('heavy pot', (SELECT id FROM equipment WHERE name = 'dutch oven'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('casserole pot', (SELECT id FROM equipment WHERE name = 'dutch oven'));
INSERT INTO equipment (name, reviewed) VALUES ('baking sheet', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('sheet pan', (SELECT id FROM equipment WHERE name = 'baking sheet'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('cookie sheet', (SELECT id FROM equipment WHERE name = 'baking sheet'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('baking tray', (SELECT id FROM equipment WHERE name = 'baking sheet'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('rimmed baking sheet', (SELECT id FROM equipment WHERE name = 'baking sheet'));
INSERT INTO equipment (name, reviewed) VALUES ('roasting pan', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('roasting tray', (SELECT id FROM equipment WHERE name = 'roasting pan'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('roaster', (SELECT id FROM equipment WHERE name = 'roasting pan'));
INSERT INTO equipment (name, reviewed) VALUES ('loaf pan', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('bread pan', (SELECT id FROM equipment WHERE name = 'loaf pan'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('loaf tin', (SELECT id FROM equipment WHERE name = 'loaf pan'));
INSERT INTO equipment (name, reviewed) VALUES ('muffin tin', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('muffin pan', (SELECT id FROM equipment WHERE name = 'muffin tin'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('cupcake pan', (SELECT id FROM equipment WHERE name = 'muffin tin'));
INSERT INTO equipment (name, reviewed) VALUES ('cake pan', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('cake tin', (SELECT id FROM equipment WHERE name = 'cake pan'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('round cake pan', (SELECT id FROM equipment WHERE name = 'cake pan'));
INSERT INTO equipment (name, reviewed) VALUES ('springform pan', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('springform tin', (SELECT id FROM equipment WHERE name = 'springform pan'));
INSERT INTO equipment (name, reviewed) VALUES ('baking dish', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('casserole dish', (SELECT id FROM equipment WHERE name = 'baking dish'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('oven dish', (SELECT id FROM equipment WHERE name = 'baking dish'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('9x13 pan', (SELECT id FROM equipment WHERE name = 'baking dish'));
INSERT INTO equipment (name, reviewed) VALUES ('oven', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('preheated oven', (SELECT id FROM equipment WHERE name = 'oven'));
INSERT INTO equipment (name, reviewed) VALUES ('grill', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('barbecue', (SELECT id FROM equipment WHERE name = 'grill'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('bbq', (SELECT id FROM equipment WHERE name = 'grill'));
INSERT INTO equipment (name, reviewed) VALUES ('blender', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('countertop blender', (SELECT id FROM equipment WHERE name = 'blender'));
INSERT INTO equipment (name, reviewed) VALUES ('immersion blender', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('stick blender', (SELECT id FROM equipment WHERE name = 'immersion blender'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('hand blender', (SELECT id FROM equipment WHERE name = 'immersion blender'));
INSERT INTO equipment (name, reviewed) VALUES ('food processor', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('processor', (SELECT id FROM equipment WHERE name = 'food processor'));
INSERT INTO equipment (name, reviewed) VALUES ('stand mixer', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('electric stand mixer', (SELECT id FROM equipment WHERE name = 'stand mixer'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('kitchenaid mixer', (SELECT id FROM equipment WHERE name = 'stand mixer'));
INSERT INTO equipment (name, reviewed) VALUES ('hand mixer', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('electric hand mixer', (SELECT id FROM equipment WHERE name = 'hand mixer'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('handheld mixer', (SELECT id FROM equipment WHERE name = 'hand mixer'));
INSERT INTO equipment (name, reviewed) VALUES ('slow cooker', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('crock pot', (SELECT id FROM equipment WHERE name = 'slow cooker'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('crockpot', (SELECT id FROM equipment WHERE name = 'slow cooker'));
INSERT INTO equipment (name, reviewed) VALUES ('pressure cooker', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('instant pot', (SELECT id FROM equipment WHERE name = 'pressure cooker'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('multicooker', (SELECT id FROM equipment WHERE name = 'pressure cooker'));
INSERT INTO equipment (name, reviewed) VALUES ('wok', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('stir-fry pan', (SELECT id FROM equipment WHERE name = 'wok'));
INSERT INTO equipment (name, reviewed) VALUES ('colander', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('strainer', (SELECT id FROM equipment WHERE name = 'colander'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('sieve', (SELECT id FROM equipment WHERE name = 'colander'));
INSERT INTO equipment (name, reviewed) VALUES ('whisk', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('balloon whisk', (SELECT id FROM equipment WHERE name = 'whisk'));
INSERT INTO equipment (name, reviewed) VALUES ('rolling pin', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('rolling-pin', (SELECT id FROM equipment WHERE name = 'rolling pin'));
INSERT INTO equipment (name, reviewed) VALUES ('mixing bowl', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('large bowl', (SELECT id FROM equipment WHERE name = 'mixing bowl'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('bowl', (SELECT id FROM equipment WHERE name = 'mixing bowl'));
INSERT INTO equipment (name, reviewed) VALUES ('cutting board', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('chopping board', (SELECT id FROM equipment WHERE name = 'cutting board'));
INSERT INTO equipment (name, reviewed) VALUES ('chef''s knife', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('chefs knife', (SELECT id FROM equipment WHERE name = 'chef''s knife'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('cook''s knife', (SELECT id FROM equipment WHERE name = 'chef''s knife'));
INSERT INTO equipment (name, reviewed) VALUES ('wire rack', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('cooling rack', (SELECT id FROM equipment WHERE name = 'wire rack'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('baking rack', (SELECT id FROM equipment WHERE name = 'wire rack'));
INSERT INTO equipment (name, reviewed) VALUES ('parchment paper', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('baking paper', (SELECT id FROM equipment WHERE name = 'parchment paper'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('baking parchment', (SELECT id FROM equipment WHERE name = 'parchment paper'));
INSERT INTO equipment (name, reviewed) VALUES ('aluminum foil', 1);
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('tin foil', (SELECT id FROM equipment WHERE name = 'aluminum foil'));
INSERT INTO equipment_aliases (alias, equipment_id) VALUES ('foil', (SELECT id FROM equipment WHERE name = 'aluminum foil'));

-- +goose Down
DROP TABLE equipment_aliases;
DROP TABLE equipment;
DROP TABLE ingredient_aliases;
DROP TABLE ingredients;
DROP TABLE unit_aliases;
DROP TABLE units;
