name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
      - name: fmt
        run: make fmt-check
      - name: install golangci-lint
        run: make tools
      - name: lint
        run: make lint
      - name: test
        run: make test
